[package]
name = "fusd"
version = "0.1.0"
edition = "2024_07"

[dependencies]
starknet = "2.15.0"
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v1.0.0" }

[dev-dependencies]
cairo_test = "2.15.0"

[[target.starknet-contract]]
sierra = true
